[server]
headless = true
port = 7860
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00c7ec"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
